### ISSUE TITLE
plugins db entry mentions a requirement on auth_oidc.

### ISSUE THREAD

**Issue by danmarsden** [LS2-CA/moodle-enrol_teameo#1]
in your moodle.org plugins db entry you have the text:
"This plugin is dependent on auth_oidc."

but - I couldn't see any auth_oidc code in your plugin and it's not listed as a dependency in your version.php.

If it is required, you need to add a dependency on it in your version.php file as described here:
https://moodledev.io/docs/apis/commonfiles/version.php#peer-dependenices

**Comment by werocool** [comment]
The "This plugin is dependent on auth_oidc." is no longer required since it support multiple type of authentification. The plugin has been updated.
