### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [LS2-CA/moodle-enrol_teameo#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin passes user data to an external service so implementation of this api is a requirement for plugins db approval.

While you don't store user data within the plugin, you do export it to an external api so you need to implement the external_link_location part of the api - but do not need some of the other parts.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy#

**Comment by werocool** [comment]
The Privacy API was added for GDPR support. Thanks.
